In [1]:
# NumPy Quick Reference
# This notebook contains essential NumPy operations for arrays, indexing, math, broadcasting, and file I/O.

import numpy as np

# 1. Creating Arrays
# -----------------
# 1D array
arr1d = np.array([1, 2, 3, 4])
print("1D array:\n", arr1d)

# 2D array
arr2d = np.array([[1, 2], [3, 4]])
print("\n2D array:\n", arr2d)

# Zeros and Ones
zeros = np.zeros((2, 3))  # 2x3 array of zeros
ones = np.ones((3,))      # 1D array of ones
print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)

# Range and Linspace
range_arr = np.arange(0, 10, 2)       # Start=0, Stop=10, Step=2
linspace_arr = np.linspace(0, 1, 5)   # 5 equally spaced numbers between 0 and 1
print("\nRange array:\n", range_arr)
print("\nLinspace array:\n", linspace_arr)

# Random arrays
rand_arr = np.random.rand(2, 2)       # 2x2 array of random floats between 0 and 1
print("\nRandom array:\n", rand_arr)


# 2. Array Properties
# -------------------
print("\nShape of arr2d:", arr2d.shape)
print("Size of arr2d:", arr2d.size)
print("Data type of arr2d:", arr2d.dtype)


# 3. Indexing & Slicing
# --------------------
print("\nAccess element [0,1]:", arr2d[0,1])
print("Slice first row:", arr2d[0, :])
print("Slice first column:", arr2d[:, 0])


# 4. Array Operations
# -------------------
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# Using NumPy functions
print("\nnp.add:", np.add(a, b))
print("np.multiply:", np.multiply(a, b))

# Matrix multiplication
mat_a = np.array([[1, 2], [3, 4]])
mat_b = np.array([[5, 6], [7, 8]])
print("\nMatrix multiplication:\n", np.dot(mat_a, mat_b))

# Transpose and reshape
print("\nTranspose of mat_a:\n", mat_a.T)
print("Reshape mat_a to (4,1):\n", mat_a.reshape((4,1)))


# 5. Useful Functions
# -------------------
arr = np.array([[1, 2], [3, 4]])
print("\nMean:", np.mean(arr))
print("Sum:", np.sum(arr))
print("Min:", np.min(arr), "Max:", np.max(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))


# 6. Broadcasting
# ----------------
# Allows operations between arrays of different shapes
mat = np.array([[1, 2], [3, 4]])
vec = np.array([10, 20])
print("\nBroadcasting addition:\n", mat + vec)


# 7. Saving & Loading Arrays
# --------------------------
np.save('example_array.npy', arr)  # Save array to file
loaded_arr = np.load('example_array.npy')
print("\nLoaded array from file:\n", loaded_arr)

# Tip: NumPy is the backbone for data analysis and ML in Python.
# Mastering array creation, manipulation, and math operations will make Pandas, ML, and deep learning much easier.


1D array:
 [1 2 3 4]

2D array:
 [[1 2]
 [3 4]]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [1. 1. 1.]

Range array:
 [0 2 4 6 8]

Linspace array:
 [0.   0.25 0.5  0.75 1.  ]

Random array:
 [[0.32204522 0.55429193]
 [0.36566322 0.93162979]]

Shape of arr2d: (2, 2)
Size of arr2d: 4
Data type of arr2d: int64

Access element [0,1]: 2
Slice first row: [1 2]
Slice first column: [1 3]

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]

np.add: [5 7 9]
np.multiply: [ 4 10 18]

Matrix multiplication:
 [[19 22]
 [43 50]]

Transpose of mat_a:
 [[1 3]
 [2 4]]
Reshape mat_a to (4,1):
 [[1]
 [2]
 [3]
 [4]]

Mean: 2.5
Sum: 10
Min: 1 Max: 4
Standard deviation: 1.118033988749895
Variance: 1.25

Broadcasting addition:
 [[11 22]
 [13 24]]

Loaded array from file:
 [[1 2]
 [3 4]]


In [2]:
# Additional Useful NumPy Functions
# ---------------------------------

arr = np.array([1, 2, 3, 4, 5])

# Mathematical operations
print("Cumulative sum:", np.cumsum(arr))       # Sum along the array cumulatively
print("Cumulative product:", np.cumprod(arr))  # Product along the array cumulatively
print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Natural log:", np.log(arr))
print("Absolute:", np.abs(np.array([-1, -2, 3])))

# Statistical functions
print("Median:", np.median(arr))
print("Percentile 25:", np.percentile(arr, 25))
print("Correlation coefficient:", np.corrcoef(arr, arr))
print("Covariance matrix:\n", np.cov(arr, arr))

# Sorting and unique
unsorted = np.array([3, 1, 4, 2, 2])
print("Sorted array:", np.sort(unsorted))
print("Unique elements:", np.unique(unsorted))

# Conditional operations
print("Elements > 2:", arr[arr > 2])
print("Where elements > 2:", np.where(arr > 2))  # Returns indices

# Stacking arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Vertical stack:\n", np.vstack((a,b)))
print("Horizontal stack:\n", np.hstack((a,b)))

# Repeating and tiling
print("Repeat elements:", np.repeat(a, 2))
print("Tile array:", np.tile(a, 3))


Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Absolute: [1 2 3]
Median: 3.0
Percentile 25: 2.0
Correlation coefficient: [[1. 1.]
 [1. 1.]]
Covariance matrix:
 [[2.5 2.5]
 [2.5 2.5]]
Sorted array: [1 2 2 3 4]
Unique elements: [1 2 3 4]
Elements > 2: [3 4 5]
Where elements > 2: (array([2, 3, 4]),)
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack:
 [1 2 3 4 5 6]
Repeat elements: [1 1 2 2 3 3]
Tile array: [1 2 3 1 2 3 1 2 3]
